application:
  subdomain: uxplay-web
  background_task: true
  upstreams:
    - location: /
      backend: http://host.lzcapp:11111/

services:
  uxplay-web-service:
    # upstream: johannvr/uxplay-web:1.0.3
    image: docker.1ms.run/johannvr/uxplay-web:1.0.3
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{.U.timezone}}
      - CUSTOM_PORT=11111
      - CUSTOM_HTTPS_PORT=11112
      - AIRPLAY_NAME={{.U.airplay_name}}
